Add validity test for coordinates to handle avoid geopy errors
pantherale0/pyfuelprices pull request #13
Opened 2024-08-26 12:57 UTC by n15c

Because of the latest fix, there is a error because one station from the data provider is missing the decimal dot in the coordinates. Therefore geopy throws an error when using the comparis data source. I implemented a small validity check of the coordinates.

@pantherale0 Maybe this should be something that could be done for all sources? Check the validity of some points (Coordinates, empty names, no ids, etc.)

2024-09-02 12:38 UTC, pantherale0 commented
Yes, is probably a good idea, although the parser should be responsible for ensuring the data is correct before loading into memory as the functions to retrieve data from sources are just too generic to ensure 100% of the required data points are available for each source. A couple of comments incoming for this PR though before I merge

2024-09-02 12:39 UTC, pantherale0 requested changes

2024-09-02 12:39 UTC, pantherale0 commented on pyfuelprices/sources/switzerland/comparis.py
> +            return False
Can we return `None` here instead?

2024-09-02 12:39 UTC, pantherale0 commented on pyfuelprices/sources/switzerland/comparis.py
> +            if station != False: #If station information is not valid, then ret val is set to False
As part of above, change to `if station:`

2024-09-30 13:02 UTC, n15c commented on pyfuelprices/sources/switzerland/comparis.py
> +            return False
Fixed

2024-10-03 22:19 UTC, pantherale0 approved these changes

2024-10-03 22:19 UTC, merged